baseURL = "https://pressers.name/"
languageCode = "en-us"
title = "The Electronic Press"
theme = [ "hugo-social-metadata", "hugo-cloak-email", "pressers.name" ]
googleAnalytics = 'G-97RTTN9JGJ'

[permalinks]
    'blog' = '/:year/:month/:day/:slug'

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
  [privacy.youtube]
    privacyEnhanced = true

[params]
  description = "Steven Presser's website - projects, writeups, talks and more"