baseURL = "https://pressers.name/"
languageCode = "en-us"
title = "The Electronic Press"
theme = [ "hugo-social-metadata", "hugo-cloak-email", "pressers.name" ]

[permalinks]
    'blog' = '/:year/:month/:day/:slug'