#!/bin/bash

CONFFILE="${1:-/etc/django-autoupdate/django-autoupdate.conf}"

source "$CONFFILE"

set -e

pushd .

trap "popd" ERR

if [ -z "$GITREPO" -o ! -e "${GITREPO}" ]
then
	echo "Must specify a git repo to work from!"
	exit 1
fi

cd "$GITREPO"
git pull > /dev/null

if [ "$TESTTARGET" ]
then
	mysqldump -u $DB_USER -p$DB_PASS $PRODDB > /tmp/db_backup.sql
	mysql -u $DB_USER -p$DB_PASS <<EOF
drop database if exists $TESTDB;
create database $TESTDB;
EOF
	mysql -u $DB_USER -p$DB_PASS $TESTDB < /tmp/db_backup.sql

	./buildenv.sh "$TESTTARGET" "$TESTSETTINGS"

	# Apache needs restarting
	service apache2 restart
	sleep 10

	# Now test...
	# Basic test - HTTP status code
	CODE=$(curl -I -L $TESTURL 2>/dev/null | head -n 1 | cut -d$' ' -f2)
	if [ "$CODE" != 200 ]
	then
		echo "Test instance returned HTTP error! ($CODE)"
		exit 2
	fi
fi

./buildenv.sh "$TARGET" "$SETTINGS"

# Apache needs restarting
service apache2 restart

sleep 10

CODE=$(curl -I -L $PRODURL 2>/dev/null | head -n 1 | cut -d$' ' -f2)
if [ "$CODE" != 200 ]
then
	echo "**** WARNING ****"
	echo "Test website passed valdation, but production did not."
fi
