#!/bin/bash

CONFFILE="${1:-/etc/django-autoupdate/django-autoupdate.conf}"

source "$CONFFILE"

set -e

pushd .

trap "popd" ERR

if [ -z "$GITREPO" -o ! -e "${GITREPO}" ]
then
	echo "Must specify a git repo to work from!"
	exit 1
fi

cd "$GITREPO"
git pull

if [ "$TESTTARGET" ]
then
	mysqldump -u $DB_USER -p$DB_PASS $PRODDB > /tmp/db_backup.sql
	mysql -u $DB_USER -p$DB_PASS <<EOF
drop database if exists $TESTDB;
create database $TESTDB;
EOF
	mysql -u $DB_USER -p$DB_PASS $TESTDB < /tmp/db_backup.sql

	rm -rf "$TESTTARGET".orig
	cp -r "$TESTTARGET" "$TESTTARGET".orig
	./buildenv.sh "$TESTTARGET" "$TESTSETTINGS"

	# Check if anything changed
	if [ -z "$(diff -rq -x '*.pyc' -x settings.py "$TESTTARGET" "$TESTTARGET".orig )" ]
	then
		rm -rf "$TESTTARGET".orig
		echo "No changes; exiting"
		exit 0
	fi

	echo "Changes detected; continuing tests"
	rm -rf "$TESTTARGET".orig

	# Apache needs restarting
	service apache2 restart
	sleep 10

	# Now test...
	# Basic test - HTTP status code
	CODE=$(curl -I -k -L $TESTURL 2>/dev/null | head -n 1 | cut -d$' ' -f2)
	if [ "$CODE" != 200 ]
	then
		echo "Test instance returned HTTP error! ($CODE)"
		exit 2
	fi
	echo "Update of test site succeeded"
fi

./buildenv.sh "$TARGET" "$SETTINGS"

# Apache needs restarting
service apache2 restart

sleep 60

CODE=$(curl -I -k -L $PRODURL 2>/dev/null | head -n 1 | cut -d$' ' -f2)
if [ "$CODE" != 200 ]
then
	echo "**** WARNING ****"
	echo "Test website passed valdation, but production did not."
	exit 2
fi
echo "Update succeeded"
